server:
  port: 8082

spring:
  application:
    name: microcollector

micro-recipient:
  url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
